# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-04-29 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField(max_length=11)),
                ('total', models.IntegerField(max_length=11)),
                ('time', models.BigIntegerField(max_length=15)),
            ],
        ),
    ]
