# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-29 08:57
from __future__ import unicode_literals

from django.db import migrations


def create_initial_products(apps, schema_editor):
    Device = apps.get_model('duo', 'Device')
    Device(node_id=1234345678, total=53457654321, time=678913245).save()
    Device(node_id=123234678, total=3457654321, time=678913245).save() 
    Device(node_id=512213678, total=34537654321, time=678913245).save() 
    Device(node_id=76345678, total=545433321, time=678913245).save() 
    Device(node_id=34345678, total=427654321, time=678913245).save() 
    Device(node_id=435345678, total=5345654321, time=678913245).save() 



class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0002_auto_20170429_0822'),
    ]

    operations = [
        migrations.RunPython(create_initial_products),
    ]
