# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0003_auto_20170429_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.IntegerField()),
                ('node_type', models.CharField(choices=[('POWER', 'Power'), ('WATER', 'Water')], default='POWER', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NodePowerArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_json', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power', to='duo.Node')),
            ],
        ),
        migrations.AlterField(
            model_name='device',
            name='total',
            field=models.FloatField(),
        ),
    ]
