# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0004_auto_20170509_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='node_id',
            field=models.CharField(max_length=15),
        ),
    ]
