# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-15 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duo', '0006_auto_20170509_1552'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.AlterField(
            model_name='nodepowerarchive',
            name='archive_json',
            field=models.TextField(default='[]'),
        ),
    ]
