sparkcore:
	./djboxsym Sparkcore.symdef > Sparkcore.sym
ap:
	./djboxsym AP1509-50SG-13.symdef > AP1509-50SG-13.sym
dht22:
	./djboxsym DHT22.symdef > DHT22.sym

esp:
	./djboxsym ESP-07.symdef > ESP-07.sym
